runtime: python38
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  SPOTIPY_CLIENT_ID: '8a5b2e8f8b074c50890ca5a6d3ef60d5'
  SPOTIPY_CLIENT_SECRET: 'ee0e9cbf57694c58aebf2006de5398ab'
  SPOTIPY_REDIRECT_URI: 'http://localhost:5000/travel'
  SECRET_KEY: '+a:a8>_7I"35Az<G^ip(U*lC@8^j?n'
  OAUTHLIB_INSECURE_TRANSPORT: 1
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  SQLALCHEMY_DATABASE_URI: 'sqlite:///sqldb.db'